name: "set up build environment"
description: "set up the build environment"
inputs:
  bot-app-setting:
    required: true
    description: "The app setting for Bot"


runs:
  using: "composite"
  steps:
    - name: Use Node 13.x jack
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '13'
    - name: Use BF CLI
      shell: pwsh
      run: npm install -g @microsoft/botframework-cli 
    - name: Use .Net sdk 6.0.x
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'  
    - name: Create appsettings file
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "appsettings.json"
        json: ${{ inputs.bot-app-setting }}
        dir: "bots/employee-finder/src/SSW.SophieBot/settings"   

    - name: Prepare working folders
      shell: pwsh
      if: env.BUILD_FLOW == 'composer'
      run: |
        $generatedDirectory = "${{ env.BOT_PROJECT_DIR }}/generated"
      
        # Clean and recreate the generated directory
        if (Test-Path $generatedDirectory)
        {
          Remove-Item -Path $generatedDirectory -Force -Recurse
        }

        $outputDirectory = "$generatedDirectory/interruption"
        New-Item -Path /. -name $outputDirectory -ItemType "directory" 
    - name: Cross train LU models
      shell: pwsh
      if: env.BUILD_FLOW == 'composer'
      run: |
        $sourceDirectory = "${{ env.BOT_PROJECT_DI }}"
        $outputDirectory = "${{ env.BOT_PROJECT_DIR }}/generated/interruption"

        # Cross train models
        bf luis:cross-train --in $sourceDirectory --out $outputDirectory --config $sourceDirectory/settings/cross-train.config.json --force

        # List generated files
        cd $outputDirectory
        ls -R            

