using System;
using System.Text.Json.Serialization;

namespace SSW.SophieBot.Employees
{
    // Generated by https://quicktype.io
    public class CrmSite
    {
        [JsonPropertyName("siteid")]
        public string Siteid { get; set; }

        [JsonPropertyName("address1_telephone1")]
        public string Address1Telephone1 { get; set; }

        [JsonPropertyName("address2_shippingmethodcode")]
        public int? Address2Shippingmethodcode { get; set; }

        [JsonPropertyName("address1_addressid")]
        public string Address1Addressid { get; set; }

        [JsonPropertyName("address1_line2")]
        public string Address1Line2 { get; set; }

        [JsonPropertyName("createdon")]
        public DateTimeOffset Createdon { get; set; }

        [JsonPropertyName("address1_postalcode")]
        public string Address1Postalcode { get; set; }

        [JsonPropertyName("address1_addresstypecode")]
        public int? Address1Addresstypecode { get; set; }

        [JsonPropertyName("address1_fax")]
        public string Address1Fax { get; set; }

        [JsonPropertyName("address1_line1")]
        public string Address1Line1 { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("address1_line3")]
        public string Address1Line3 { get; set; }

        [JsonPropertyName("address1_shippingmethodcode")]
        public int? Address1Shippingmethodcode { get; set; }

        [JsonPropertyName("emailaddress")]
        public string Emailaddress { get; set; }

        [JsonPropertyName("address2_addresstypecode")]
        public int? Address2Addresstypecode { get; set; }

        [JsonPropertyName("versionnumber")]
        public int? Versionnumber { get; set; }

        [JsonPropertyName("_modifiedby_value")]
        public string ModifiedbyValue { get; set; }

        [JsonPropertyName("modifiedon")]
        public DateTimeOffset Modifiedon { get; set; }

        [JsonPropertyName("timezonecode")]
        public int? Timezonecode { get; set; }

        [JsonPropertyName("_createdby_value")]
        public string CreatedbyValue { get; set; }

        [JsonPropertyName("organizationid")]
        public string Organizationid { get; set; }

        [JsonPropertyName("address1_city")]
        public string Address1City { get; set; }

        [JsonPropertyName("address2_addressid")]
        public string Address2Addressid { get; set; }

        [JsonPropertyName("address1_country")]
        public string Address1Country { get; set; }

        [JsonPropertyName("address1_stateorprovince")]
        public string Address1Stateorprovince { get; set; }

        [JsonPropertyName("address1_telephone2")]
        public string Address1Telephone2 { get; set; }

        [JsonPropertyName("address2_name")]
        public string Address2Name { get; set; }

        [JsonPropertyName("address1_intitude")]
        public string Address1intitude { get; set; }

        [JsonPropertyName("address1_county")]
        public string Address1County { get; set; }

        [JsonPropertyName("address2_country")]
        public string Address2Country { get; set; }

        [JsonPropertyName("address2_telephone2")]
        public string Address2Telephone2 { get; set; }

        [JsonPropertyName("address2_county")]
        public string Address2County { get; set; }

        [JsonPropertyName("address2_line2")]
        public string Address2Line2 { get; set; }

        [JsonPropertyName("timezoneruleversionnumber")]
        public string Timezoneruleversionnumber { get; set; }

        [JsonPropertyName("overriddencreatedon")]
        public string Overriddencreatedon { get; set; }

        [JsonPropertyName("address2_city")]
        public string Address2City { get; set; }

        [JsonPropertyName("address2_postofficebox")]
        public string Address2Postofficebox { get; set; }

        [JsonPropertyName("importsequencenumber")]
        public string Importsequencenumber { get; set; }

        [JsonPropertyName("address1_latitude")]
        public string Address1Latitude { get; set; }

        [JsonPropertyName("_createdonbehalfby_value")]
        public string CreatedonbehalfbyValue { get; set; }

        [JsonPropertyName("address2_stateorprovince")]
        public string Address2Stateorprovince { get; set; }

        [JsonPropertyName("address2_fax")]
        public string Address2Fax { get; set; }

        [JsonPropertyName("address1_upszone")]
        public string Address1Upszone { get; set; }

        [JsonPropertyName("address1_name")]
        public string Address1Name { get; set; }

        [JsonPropertyName("address1_postofficebox")]
        public string Address1Postofficebox { get; set; }

        [JsonPropertyName("address2_latitude")]
        public string Address2Latitude { get; set; }

        [JsonPropertyName("address1_telephone3")]
        public string Address1Telephone3 { get; set; }

        [JsonPropertyName("address2_upszone")]
        public string Address2Upszone { get; set; }

        [JsonPropertyName("address2_intitude")]
        public string Address2intitude { get; set; }

        [JsonPropertyName("_modifiedonbehalfby_value")]
        public string ModifiedonbehalfbyValue { get; set; }

        [JsonPropertyName("msdyn_migrationinfo")]
        public string MsdynMigrationinfo { get; set; }

        [JsonPropertyName("address2_utcoffset")]
        public string Address2Utcoffset { get; set; }

        [JsonPropertyName("address2_postalcode")]
        public string Address2Postalcode { get; set; }

        [JsonPropertyName("address2_line1")]
        public string Address2Line1 { get; set; }

        [JsonPropertyName("address2_telephone1")]
        public string Address2Telephone1 { get; set; }

        [JsonPropertyName("msdyn_migrationrunindex")]
        public string MsdynMigrationrunindex { get; set; }

        [JsonPropertyName("utcconversiontimezonecode")]
        public string Utcconversiontimezonecode { get; set; }

        [JsonPropertyName("address1_utcoffset")]
        public string Address1Utcoffset { get; set; }

        [JsonPropertyName("msdyn_migrationstatus")]
        public int? MsdynMigrationstatus { get; set; }

        [JsonPropertyName("address2_telephone3")]
        public string Address2Telephone3 { get; set; }

        [JsonPropertyName("address2_line3")]
        public string Address2Line3 { get; set; }
    }
}
