name: "set up build environment"
description: "set up the build environment"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4

    - name: Use Node 13.x jack
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '13'
    - name: Use BF CLI
      run: npm install -g @microsoft/botframework-cli 
    - name: Use .Net sdk 6.0.x
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'      

