using System;
using System.Text.Json.Serialization;

namespace SSW.SophieBot.Employees
{
    // Generated by https://quicktype.io
    public class CrmEmployee
    {
        [JsonPropertyName("ssw_jobtitle")]
        public int SswJobtitle { get; set; }

        [JsonPropertyName("mobilephone")]
        public string Mobilephone { get; set; }

        [JsonPropertyName("address1_country")]
        public string Address1Country { get; set; }

        [JsonPropertyName("islicensed")]
        public bool Islicensed { get; set; }

        [JsonPropertyName("personalemailaddress")]
        public string Personalemailaddress { get; set; }

        [JsonPropertyName("ssw_dateofbirth")]
        public DateTime SswDateofbirth { get; set; }

        [JsonPropertyName("ssw_tshirtsize")]
        public int SswTshirtsize { get; set; }

        [JsonPropertyName("accessmode")]
        public int Accessmode { get; set; }

        [JsonPropertyName("exchangerate")]
        public int Exchangerate { get; set; }

        [JsonPropertyName("ssw_delveurl")]
        public string SswDelveurl { get; set; }

        [JsonPropertyName("systemuserid")]
        public string Systemuserid { get; set; }

        [JsonPropertyName("windowsliveid")]
        public string Windowsliveid { get; set; }

        [JsonPropertyName("ssw_publicprofileurl")]
        public string SswPublicprofileurl { get; set; }

        [JsonPropertyName("outgoingemaildeliverymethod")]
        public int Outgoingemaildeliverymethod { get; set; }

        [JsonPropertyName("address2_shippingmethodcode")]
        public int Address2Shippingmethodcode { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("_siteid_value")]
        public string SiteidValue { get; set; }

        [JsonPropertyName("address1_postalcode")]
        public string Address1Postalcode { get; set; }

        [JsonPropertyName("modifiedon")]
        public DateTime Modifiedon { get; set; }

        [JsonPropertyName("preferredaddresscode")]
        public int Preferredaddresscode { get; set; }

        [JsonPropertyName("preferredemailcode")]
        public int Preferredemailcode { get; set; }

        [JsonPropertyName("address1_shippingmethodcode")]
        public int Address1Shippingmethodcode { get; set; }

        [JsonPropertyName("address1_composite")]
        public string Address1Composite { get; set; }

        [JsonPropertyName("lastname")]
        public string Lastname { get; set; }

        [JsonPropertyName("ssw_blogurl")]
        public string SswBlogurl { get; set; }

        [JsonPropertyName("caltype")]
        public int Caltype { get; set; }

        [JsonPropertyName("ssw_githuburl")]
        public string SswGithuburl { get; set; }

        [JsonPropertyName("_calendarid_value")]
        public string CalendaridValue { get; set; }

        [JsonPropertyName("firstname")]
        public string Firstname { get; set; }

        [JsonPropertyName("userlicensetype")]
        public int Userlicensetype { get; set; }

        [JsonPropertyName("yomifullname")]
        public string Yomifullname { get; set; }

        [JsonPropertyName("_businessunitid_value")]
        public string BusinessunitidValue { get; set; }

        [JsonPropertyName("incomingemaildeliverymethod")]
        public int Incomingemaildeliverymethod { get; set; }

        [JsonPropertyName("ssw_defaultrate")]
        public int SswDefaultrate { get; set; }

        [JsonPropertyName("issyncwithdirectory")]
        public bool Issyncwithdirectory { get; set; }

        [JsonPropertyName("middlename")]
        public string Middlename { get; set; }

        [JsonPropertyName("setupuser")]
        public bool Setupuser { get; set; }

        [JsonPropertyName("fullname")]
        public string Fullname { get; set; }

        [JsonPropertyName("employeeid")]
        public string Employeeid { get; set; }

        [JsonPropertyName("timezoneruleversionnumber")]
        public int Timezoneruleversionnumber { get; set; }

        [JsonPropertyName("address1_addressid")]
        public string Address1Addressid { get; set; }

        [JsonPropertyName("createdon")]
        public DateTime Createdon { get; set; }

        [JsonPropertyName("ssw_twitterusername")]
        public string SswTwitterusername { get; set; }

        [JsonPropertyName("address1_stateorprovince")]
        public string Address1Stateorprovince { get; set; }

        [JsonPropertyName("deletedstate")]
        public int Deletedstate { get; set; }

        [JsonPropertyName("defaultfilterspopulated")]
        public bool Defaultfilterspopulated { get; set; }

        [JsonPropertyName("defaultodbfoldername")]
        public string Defaultodbfoldername { get; set; }

        [JsonPropertyName("_defaultmailbox_value")]
        public string DefaultmailboxValue { get; set; }

        [JsonPropertyName("invitestatuscode")]
        public int Invitestatuscode { get; set; }

        [JsonPropertyName("versionnumber")]
        public int Versionnumber { get; set; }

        [JsonPropertyName("azureactivedirectorystringid")]
        public string Azureactivedirectorystringid { get; set; }

        [JsonPropertyName("address1_line1")]
        public string Address1Line1 { get; set; }

        [JsonPropertyName("address1_addresstypecode")]
        public int Address1Addresstypecode { get; set; }

        [JsonPropertyName("isintegrationuser")]
        public bool Isintegrationuser { get; set; }

        [JsonPropertyName("ssw_profilecategory")]
        public int SswProfilecategory { get; set; }

        [JsonPropertyName("_transactioncurrencyid_value")]
        public string TransactioncurrencyidValue { get; set; }

        [JsonPropertyName("utcconversiontimezonecode")]
        public int Utcconversiontimezonecode { get; set; }

        [JsonPropertyName("ssw_smartphoneos")]
        public int SswSmartphoneos { get; set; }

        [JsonPropertyName("ssw_publicphotoalbumurl")]
        public string SswPublicphotoalbumurl { get; set; }

        [JsonPropertyName("salutation")]
        public string Salutation { get; set; }

        [JsonPropertyName("ssw_skypeusername")]
        public string SswSkypeusername { get; set; }

        [JsonPropertyName("_modifiedby_value")]
        public string ModifiedbyValue { get; set; }

        [JsonPropertyName("ssw_lastsyncdate")]
        public DateTime SswLastsyncdate { get; set; }

        [JsonPropertyName("_createdby_value")]
        public string CreatedbyValue { get; set; }

        [JsonPropertyName("address1_city")]
        public string Address1City { get; set; }

        [JsonPropertyName("preferredphonecode")]
        public int Preferredphonecode { get; set; }

        [JsonPropertyName("address2_addresstypecode")]
        public int Address2Addresstypecode { get; set; }

        [JsonPropertyName("domainname")]
        public string Domainname { get; set; }

        [JsonPropertyName("_ssw_employeecontactid_value")]
        public string SswEmployeecontactidValue { get; set; }

        [JsonPropertyName("userpuid")]
        public string Userpuid { get; set; }

        [JsonPropertyName("ssw_datestarted")]
        public DateTime SswDatestarted { get; set; }

        [JsonPropertyName("identityid")]
        public int Identityid { get; set; }

        [JsonPropertyName("isdisabled")]
        public bool Isdisabled { get; set; }

        [JsonPropertyName("address2_addressid")]
        public string Address2Addressid { get; set; }

        [JsonPropertyName("emailrouteraccessapproval")]
        public int Emailrouteraccessapproval { get; set; }

        [JsonPropertyName("organizationid")]
        public string Organizationid { get; set; }

        [JsonPropertyName("internalemailaddress")]
        public string Internalemailaddress { get; set; }

        [JsonPropertyName("displayinserviceviews")]
        public bool Displayinserviceviews { get; set; }

        [JsonPropertyName("_parentsystemuserid_value")]
        public string ParentsystemuseridValue { get; set; }

        [JsonPropertyName("isemailaddressapprovedbyo365admin")]
        public bool Isemailaddressapprovedbyo365Admin { get; set; }

        [JsonPropertyName("_queueid_value")]
        public string QueueidValue { get; set; }

        [JsonPropertyName("ssw_defaultrate_base")]
        public int SswDefaultrateBase { get; set; }

        [JsonPropertyName("ssw_category")]
        public int SswCategory { get; set; }

        [JsonPropertyName("ssw_istimeproemp")]
        public bool SswIstimeproemp { get; set; }

        [JsonPropertyName("ownerid")]
        public string Ownerid { get; set; }

        [JsonPropertyName("address2_county")]
        public string Address2County { get; set; }

        [JsonPropertyName("address2_telephone3")]
        public string Address2Telephone3 { get; set; }

        [JsonPropertyName("address1_latitude")]
        public string Address1Latitude { get; set; }

        [JsonPropertyName("governmentid")]
        public string Governmentid { get; set; }

        [JsonPropertyName("ssw_facebookurl")]
        public string SswFacebookurl { get; set; }

        [JsonPropertyName("nickname")]
        public string Nickname { get; set; }

        [JsonPropertyName("address2_fax")]
        public string Address2Fax { get; set; }

        [JsonPropertyName("entityimage")]
        public string Entityimage { get; set; }

        [JsonPropertyName("address2_intitude")]
        public string Address2intitude { get; set; }

        [JsonPropertyName("address1_telephone1")]
        public string Address1Telephone1 { get; set; }

        [JsonPropertyName("sharepointemailaddress")]
        public string Sharepointemailaddress { get; set; }

        [JsonPropertyName("entityimage_timestamp")]
        public string EntityimageTimestamp { get; set; }

        [JsonPropertyName("ssw_datefinished")]
        public string SswDatefinished { get; set; }

        [JsonPropertyName("applicationid")]
        public string Applicationid { get; set; }

        [JsonPropertyName("address1_name")]
        public string Address1Name { get; set; }

        [JsonPropertyName("_modifiedonbehalfby_value")]
        public string ModifiedonbehalfbyValue { get; set; }

        [JsonPropertyName("ssw_phoneextension")]
        public string SswPhoneextension { get; set; }

        [JsonPropertyName("ssw_aboutmeaudiourl")]
        public string SswAboutmeaudiourl { get; set; }

        [JsonPropertyName("address2_postofficebox")]
        public string Address2Postofficebox { get; set; }

        [JsonPropertyName("disabledreason")]
        public string Disabledreason { get; set; }

        [JsonPropertyName("passportlo")]
        public string Passportlo { get; set; }

        [JsonPropertyName("address1_fax")]
        public string Address1Fax { get; set; }

        [JsonPropertyName("ssw_smartphonewifimacaddress")]
        public string SswSmartphonewifimacaddress { get; set; }

        [JsonPropertyName("address2_postalcode")]
        public string Address2Postalcode { get; set; }

        [JsonPropertyName("ssw_dietarynote")]
        public string SswDietarynote { get; set; }

        [JsonPropertyName("ssw_timepropwd")]
        public string SswTimepropwd { get; set; }

        [JsonPropertyName("ssw_youtubeplaylistid")]
        public string SswYoutubeplaylistid { get; set; }

        [JsonPropertyName("_territoryid_value")]
        public string TerritoryidValue { get; set; }

        [JsonPropertyName("msdyn_migrationinfo")]
        public string MsdynMigrationinfo { get; set; }

        [JsonPropertyName("jobtitle")]
        public string Jobtitle { get; set; }

        [JsonPropertyName("yomilastname")]
        public string Yomilastname { get; set; }

        [JsonPropertyName("address2_telephone1")]
        public string Address2Telephone1 { get; set; }

        [JsonPropertyName("mobilealertemail")]
        public string Mobilealertemail { get; set; }

        [JsonPropertyName("address2_country")]
        public string Address2Country { get; set; }

        [JsonPropertyName("entityimageid")]
        public string Entityimageid { get; set; }

        [JsonPropertyName("overriddencreatedon")]
        public string Overriddencreatedon { get; set; }

        [JsonPropertyName("address2_latitude")]
        public string Address2Latitude { get; set; }

        [JsonPropertyName("processid")]
        public string Processid { get; set; }

        [JsonPropertyName("stageid")]
        public string Stageid { get; set; }

        [JsonPropertyName("ssw_playlist")]
        public string SswPlaylist { get; set; }

        [JsonPropertyName("address2_city")]
        public string Address2City { get; set; }

        [JsonPropertyName("photourl")]
        public string Photourl { get; set; }

        [JsonPropertyName("address1_line3")]
        public string Address1Line3 { get; set; }

        [JsonPropertyName("ssw_xeroemployeeid")]
        public string SswXeroemployeeid { get; set; }

        [JsonPropertyName("address1_telephone2")]
        public string Address1Telephone2 { get; set; }

        [JsonPropertyName("address1_intitude")]
        public string Address1intitude { get; set; }

        [JsonPropertyName("address2_composite")]
        public string Address2Composite { get; set; }

        [JsonPropertyName("address1_county")]
        public string Address1County { get; set; }

        [JsonPropertyName("skills")]
        public string Skills { get; set; }

        [JsonPropertyName("_createdonbehalfby_value")]
        public string CreatedonbehalfbyValue { get; set; }

        [JsonPropertyName("ssw_datedisabled")]
        public string SswDatedisabled { get; set; }

        [JsonPropertyName("address2_upszone")]
        public string Address2Upszone { get; set; }

        [JsonPropertyName("ssw_sameasjobtitle")]
        public string SswSameasjobtitle { get; set; }

        [JsonPropertyName("address2_name")]
        public string Address2Name { get; set; }

        [JsonPropertyName("msdyn_gdproptout")]
        public string MsdynGdproptout { get; set; }

        [JsonPropertyName("traversedpath")]
        public string Traversedpath { get; set; }

        [JsonPropertyName("yomifirstname")]
        public string Yomifirstname { get; set; }

        [JsonPropertyName("passporthi")]
        public string Passporthi { get; set; }

        [JsonPropertyName("importsequencenumber")]
        public string Importsequencenumber { get; set; }

        [JsonPropertyName("yomimiddlename")]
        public string Yomimiddlename { get; set; }

        [JsonPropertyName("ssw_shortdescription")]
        public string SswShortdescription { get; set; }

        [JsonPropertyName("applicationidstring")]
        public string Applicationidstring { get; set; }

        [JsonPropertyName("address2_line2")]
        public string Address2Line2 { get; set; }

        [JsonPropertyName("address1_line2")]
        public string Address1Line2 { get; set; }

        [JsonPropertyName("ssw_details")]
        public string SswDetails { get; set; }

        [JsonPropertyName("ssw_hideprofile")]
        public string SswHideprofile { get; set; }

        [JsonPropertyName("ssw_chinaid")]
        public string SswChinaid { get; set; }

        [JsonPropertyName("msdyn_migrationrunindex")]
        public string MsdynMigrationrunindex { get; set; }

        [JsonPropertyName("address2_stateorprovince")]
        public string Address2Stateorprovince { get; set; }

        [JsonPropertyName("address2_line3")]
        public string Address2Line3 { get; set; }

        [JsonPropertyName("entityimage_url")]
        public string EntityimageUrl { get; set; }

        [JsonPropertyName("address1_telephone3")]
        public string Address1Telephone3 { get; set; }

        [JsonPropertyName("address2_line1")]
        public string Address2Line1 { get; set; }

        [JsonPropertyName("_positionid_value")]
        public string PositionidValue { get; set; }

        [JsonPropertyName("address1_postofficebox")]
        public string Address1Postofficebox { get; set; }

        [JsonPropertyName("yammeremailaddress")]
        public string Yammeremailaddress { get; set; }

        [JsonPropertyName("ssw_note")]
        public string SswNote { get; set; }

        [JsonPropertyName("ssw_workhours")]
        public string SswWorkhours { get; set; }

        [JsonPropertyName("address1_upszone")]
        public string Address1Upszone { get; set; }

        [JsonPropertyName("_mobileofflineprofileid_value")]
        public string MobileofflineprofileidValue { get; set; }

        [JsonPropertyName("address1_utcoffset")]
        public string Address1Utcoffset { get; set; }

        [JsonPropertyName("ssw_linkedinurl")]
        public string SswLinkedinurl { get; set; }

        [JsonPropertyName("yammeruserid")]
        public string Yammeruserid { get; set; }

        [JsonPropertyName("msdyn_migrationstatus")]
        public string MsdynMigrationstatus { get; set; }

        [JsonPropertyName("address2_utcoffset")]
        public string Address2Utcoffset { get; set; }

        [JsonPropertyName("homephone")]
        public string Homephone { get; set; }

        [JsonPropertyName("address2_telephone2")]
        public string Address2Telephone2 { get; set; }
    }
}
