name: Build Bot Apps

on:
  push:
    branches:
      - main
    paths:
      - apps/**
      - .github/workflows/SSW.SophieBot.Web.yml

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: check out branch
        uses: actions/checkout@v2

      - name: set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"

      - name: install and build
        run: |
          yarn install
          yarn build
        working-directory: apps/SSW.SophieBot.Web

      - name: upload to storage account
        uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: apps/SSW.SophieBot.Web/dist
          container_name: "$web"
          connection_string: ${{ secrets.WEBBLOBSTORAGECONNECTIONSTRING }}
          sync: true
