name: Build and Test

on:
  pull_request:
    paths-ignore:
      - '_docs/**'
  push:
    branches:
      - main
    paths:
      - 'bots/**'
      - 'libraries/**'
      - 'services/**'
      - .github/workflows/SSW.SophieBot.test.yml
  
concurrency:
  group: SSWSophieBot-BuildAndTest
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use .Net sdk 6.0.x
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'
      
      - name: Build all
        run: .\build-all.ps1
        working-directory: ./_scripts

      - name: Test all
        run: .\test-all.ps1
        working-directory: ./_scripts

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
