name: Test

on:
  pull_request:
    paths-ignore:
      - '_docs/**'
  
defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use .Net Core sdk
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      # dotnet test
      - name: Test solution
        run: |
          cd ${{ github.workspace }}
          dotnet test --verbosity normal